### ISSUE TITLE
RNG discrepancies resulting in test failures

### ISSUE THREAD

**Issue by bjoelle** [revbayes/revbayes#139]
There is an issue where tests pass on a local machine but then fail on the github-actions. Seen in PR #136 last time.

It seems related to changes to the RNG in Boost which leads to different versions producing different outputs. I'm not sure why the FBD test was the only affected, it could be due to it being longer and/or using more operators.

I'm opening this issue mostly as a record in case people run into it again.

**Comment by willpett** [comment]
I think this is actually caused by different implementations of `libm` on different platforms, leading to slightly different results from standard math functions like `exp`, `log`, `sin` etc. Switching to a common implementation across all platforms (`openlibm`) has solved this issue on the `fbd` branch.
