### ISSUE TITLE
Site-heterogeneous rate matrices

### ISSUE THREAD

**Issue by berkalpay** [revbayes/revbayes#153]
**Describe the analysis you'd like to do.**
I would like to incorporate site-heterogeneous rate matrices (e.g. [CAT by Lartillot and Philippe](https://pubmed.ncbi.nlm.nih.gov/15014145/)) into my models. 

**Describe alternatives you've considered**
All of the examples in RevBayes documentation assume a rate matrix constant with respect to site. It seems for the parameter Q to [dnPhyloCTMC](https://revbayes.github.io/documentation/dnPhyloCTMC.html), "site-mixture rate matrices" can be passed. However, I've found no documentation elaborating on this.

I also have a [related post](https://groups.google.com/g/revbayes-users/c/jDWXR-cv0dI) on the forum.

**Comment by bredelings** [comment]
You can do the following:
```
ff ~ dnDirichlet([1,1])
seq ~ dnPhyloCTMC(tree=topology,Q=[Q1,Q2],siteMatrices=ff)
```
I made a simple example were Q1 and Q2 are both GTR with the same exchangeabilities but different frequencies, and it seemed to work.

**Comment by berkalpay** [comment]
I may be mistaken but it seems that this models each site as a mixture of GTRs, but that this mixture is constant across sites. What I am looking for is e.g. site 1 to operate under Q1, site 2 to operate under Q2, and site 3 to operate under Q1. The assignment of rate matrices to sites would itself be a random variable. Does such a functionality exist?

**Comment by willpett** [comment]
The `siteMatrices` argument determines the mixture frequencies of `Q`. That is, the likelihood is computed at each site as a mixture of the matrices provided in `Q` with mixture frequencies/weights determined by `siteMatrices`. So, if you wanted to implement the CAT model, you would treat the vector `Q` as a draw from a Dirichlet process, and then provide `siteMatrices` with the stick-breaking representation of the mixture weights of that process.

However, I wouldn't recommend trying this. It would be horribly slow and probably would not mix well at all. The `siteMatrices` wasn't really intended to used with large numbers of matrices. It was implemented with finite mixtures of a small number of matrices in mind. In order to use something like the CAT model in RevBayes, a completely different implementation would be required under the hood to make it anywhere near as efficient as PhyloBayes.

Of course, getting efficient site-heterogeneous models implemented in RevBayes is and has been a long term goal. But right now, if you want to use the CAT model, you should use PhyloBayes.

Alternatively, you could try an empirical mixture model (e.g. like C10-C60) which should be much easier to get going in RevBayes. There are a variety of options out there for this, some of which are implemented in IQ-TREE which you could look at. The models described [here](https://www.biorxiv.org/content/10.1101/794263v1?rss=1) have RevBayes scripts provided, so that might be worth a try.
