### ISSUE TITLE
segmentation fault or hang dealing with many topological constraints

### ISSUE THREAD

**Issue by zhangchicool** [revbayes/revbayes#159]
The morphological dataset has 54 hard topological constraints in a FBD dating analysis (attached). It fail to launch in both Mac (Big Sur 11.2.2) and Ubuntu (20.04.2 LTS). Mac gave "segmentation fault" and Ubuntu hung after saying "Successfully read one character matrix from file 'pterosaur_discrete.nex'".  Removing some constraints, say just leaving 5 to 10 constraints enabled, the program seems to run fine.

The same full set of constraints was tested in MrBayes and had no problem to run (also attached).

RevBayes was compiled from source from the develop branch (Build from development (rapture-641-g7d4aab) on Mon Mar  8). 

Thanks for looking at this issue.

[topo_constraints.zip](https://github.com/revbayes/revbayes/files/6106641/topo_constraints.zip)

**Comment by zhangchicool** [comment]
Another question related, does RevBayes have an option to set multiple backbone constraints? 

For example, let A B C form a clade, D E F form another clade, etc. and the rest of the taxa, say, X Y Z, can move freely in the tree (in or out of the defined constraints).

**Comment by bredelings** [comment]
There seems to be a problem trying to draw an initial value that fits the constraints.

After I added a hack to my local code, the example ran fine:
```
diff --git a/src/core/distributions/phylogenetics/tree/birthdeath/AbstractBirthDeathProcess.cpp b/src/core/distributions/phylogenetics/tree/birthdeath/AbstractBirthDeathProcess.cpp
index 52061613..64e2e0ba 100644
--- a/src/core/distributions/phylogenetics/tree/birthdeath/AbstractBirthDeathProcess.cpp
+++ b/src/core/distributions/phylogenetics/tree/birthdeath/AbstractBirthDeathProcess.cpp
@@ -10,6 +10,8 @@
 #include "RbMathCombinatorialFunctions.h"
 #include "TopologyNode.h"
 #include "AbstractRootedTreeDistribution.h"
+#include "RandomNumberGenerator.h"
+#include "RandomNumberFactory.h"
 #include "Tree.h"
 
 namespace RevBayesCore { class Taxon; }
@@ -127,9 +129,15 @@ std::vector<double> AbstractBirthDeathProcess::simulateDivergenceTimes(size_t n,
     {
         double t = 0.0;
 
+        auto rng = GLOBAL_RNG;
+        double u = rng->uniform01();
+        t = min + u*(origin-min);
+
+        /*
         do {
             t = simulateDivergenceTime(origin, present);
         } while ( t < min );
+        */
 
         times[i] = t;
     }
```

**Comment by willgearty** [comment]
Just wanted to mention that this "hack" has also fixed my hanging issues related to lots of topological constraints. This has most certainly saved me many hours of waiting in the future!

**Comment by davidcerny** [comment]
After some minor changes necessitated by other RevBayes developments since the original issue was submitted (`min` -> `min_age` and `max` -> `max_age` in the taxon age file; `dnEFBDP` -> `dnFBDP` in the script), @zhangchicool's dataset now runs without any issues, likely thanks to @bjoelle's PR #453.

As for the (never answered) question:

> Another question related, does RevBayes have an option to set multiple backbone constraints?
> 
> For example, let A B C form a clade, D E F form another clade, etc. and the rest of the taxa, say, X Y Z, can move freely in the tree (in or out of the defined constraints).

Yes, this can be accomplished by passing a tree to the `backbone` argument of the `dnConstrainedTopology()` distribution. Such a tree would include A, B, C, D, E, and F, but not X, Y, and Z, which would be free to attach wherever favored by the data. It's not entirely clear to me in what situation one might need multiple backbone trees, but the distribution does allow it: the `backbone` argument accepts both a single tree and a vector of trees.

Closing this now.
