### ISSUE TITLE
[BUG] Specifying an initial tree in dnBDSTP overwrites fossil ages

### ISSUE THREAD

**Issue by davidcerny** [revbayes/revbayes#354]
**Describe the bug**
To accommodate tip age uncertainty in the FBD-specimen process, we can place a uniform prior on the age range associated with each specimen, and use MCMC to sample exact ages in proportion to their posterior density (see "Sampling Fossil Occurrence Ages" in the [current FBD-specimen tutorial](https://revbayes.github.io/tutorials/fbd/fbd_specimen.html)). To do this, we have to access the age range stored in the `TimeInterval` member of class `Taxon`:

```
fossils = fbd_tree.getFossils()
for(i in 1:fossils.size())
{
    t[i] := tmrca(fbd_tree, clade(fossils[i]))
    a_i = fossils[i].getMinAge()
    b_i = fossils[i].getMaxAge()

    F[i] ~ dnUniform(t[i] - b_i, t[i] - a_i)
    F[i].clamp( 0 )
}
```

The `TimeInterval` member is initialized using `TaxonReader.cpp`, but specifying the `initialTree` argument in `dnBDSTP` apparently overwrites it, setting both the minimum and maximum age of each fossil in the tree to 0. As a result, initializing an FBD-specimen analysis using a user-supplied starting tree is only viable if the user is willing to treat specimen ages as fixed values.

**To Reproduce**
See [example script 1](https://github.com/revbayes/revbayes/files/11523634/test.txt), [data 1](https://github.com/revbayes/revbayes/files/11523629/data.zip), and [example script 2](https://github.com/revbayes/revbayes/files/11523633/test_2.txt), [data 2](https://github.com/revbayes/revbayes/files/11523628/data_2.zip). One absolute path has to be changed. A draw from `dnBDSTP` that does not specify an `initialTree` results in the expected maximum and minimum ages being printed to the screen; commenting it out and drawing after an `initialTree` is specified results in these being equal to 0.

**Expected behavior**
Specifying an `initialTree` should not alter the `TimeInterval` member of the objects stored in the `taxa` vector.

**Screenshots**
N/A

**Computer info**
macOS v12.6.5, RevBayes 1.2.1, latest `development` version (rapture-2179-g991117).

**Comment by afmagee** [comment]
This is definitely not something one would expect _a priori_. The following is not yet a solution to the problem, just a sketch of what's going on so as to help arrive at a solution.

When not using an `initialTree`, the BDSTP calls the `startingTreeSimulator`. The `startingTreeSimulator` explicitly puts tip nodes into the tree using the `taxa` object which is provided to the BDSTP. As the taxa are where the age information is stored, this leads to a tree that has taxa that know their ages.

When using an `initialTree`, the BDSTP sets the tree equal to the initial tree. The initial tree's taxa have never been told how old they are, so this tree now has taxa that do not know their age.

While it's handy, initialTree is provoking this problem because it is a bit outside of Rev's usual notion of how to do things. Depending on how you look at it, the problem is either as above that the initial tree was never told how old its tips are, or that the BDSTP fails to link the taxa to the tree. Between these two options, it seems like giving the work to the BDSTP would be the more-consistent thing to do. 

Perhaps be a separate function would be in order so that any other tree models which eventually adopt an initialTree framework can do the same. Something like a `startingTreeInitializer(Tree &target, Tree &treeToCopy, std::vector<Taxon> &taxaToCopy)` which ensures both that the tree and taxa get appropriately set? Perhaps @hoehna has an opinion.

**Comment by hoehna** [comment]
Yes, this probably needs fixing. Would `fbd_tree.setValue( initial_tree )` work for you?

**Comment by davidcerny** [comment]
Apologies for responding so late – no, unfortunately, passing a starting tree to the distribution via the `.setValue()` method instead of the `initialTree` argument only reproduces the problem.

I 100% agree with @afmagee that there is something unsatisfying about having to supply a handcrafted starting tree anyway, but unfortunately, it seems to be the only way to get some complex FBD analyses off the ground. In the long term, the option suggested by @bredelings – simulate approximately from the prior, so that you don't have to reject an initial state even if its log density evaluates to negative infinity – would probably be the best option, but my understanding is that implementing it is not on the immediate agenda. (Unfortunately, it's above my paygrade to do it myself.)

I really like the idea of a `startingTreeInitializer()` function though, and could try my hand at writing it. Just to make sure I understand it conceptually, though, what would the `target` argument correspond to? An initial draw from the distribution before we replace it by the user-supplied tree? If so, wouldn't that defeat the purpose of the function, given that obtaining a draw like that is precisely the problem we are trying to circumvent?

**Comment by afmagee** [comment]
Oh, that was just be not being sure if the function works best as a void function that would alter the BDSTP's value in place or a function that returns a tree.

    void startingTreeInitializer1(Tree &treeToChange, Tree &treeToCopy, std::vector<Taxon> &taxaToCopy) {
      // do stuff to treeToChange here
    }
    
    Tree& startingTreeInitializer2(std::vector<Taxon> &taxaToCopy) {
      // make a new tree here
      return *newTree;
    }

Then lines 169-172 of the BDSTP would be replaced by either
    
    if (t != nullptr) 
    {
        startingTreeInitializer1(value,t,taxa);
    }

or something like 

    if (t != nullptr)
    {
        value = startingTreeInitializer2(t,taxa);
    }

I've had trouble with setting trees equal, so that last option might actually require calling `.clone()`. Line 171 had been just `value = t;` but that was producing segfaults in a script of mine, which is why it's currently `value = t->clone();` I had similar trouble with a tree move setting a tree equal instead of cloning it.

**Comment by davidcerny** [comment]
Hmm, I really like the former option. Will give a try to implementing it asap. Would `TreeUtilities` be a good place to put a function like this?

**Comment by afmagee** [comment]
Seems a pretty natural place to me. 

JFYI there's a test for the last initialTree bug squashed here: https://github.com/revbayes/revbayes/tree/development/tests/test_initialTree. Once you've got the new code working and it passes existing tests, appending to that script a test that captures the taxon age setting behavior might be a good idea.
