### ISSUE TITLE
[BUG] dnFBDP Error when root node with fossils

### ISSUE THREAD

**Issue by mhDu** [revbayes/revbayes#424]
**Describe the bug**
When using the FBD model on a fixed tree with fossils, if a tree's root node has fossils, it will prompt an error: 
`Error:Tree height and root age values must match when root age is not a stochastic node.` 

**To Reproduce**
I have uploaded the file I used [FBD_bug.zip](https://github.com/revbayes/revbayes/files/13976832/FBD_bug.zip). The "tree.tre" is the original tree, and the root node of this tree has a fossil collection (as shown in the figure below as t358_1). If this fossil is removed, the resulting tree "tree_removed.tre" can run normally.
<img width="1094" alt="image" src="https://github.com/revbayes/revbayes/assets/51898298/f0a1ffdf-8efd-470e-b84e-a9c33f8997f9">

My Rev script uses a constant rate FBD model with mass extinction, but I feel this problem may also occur in other FBD models.

**Expected behavior**
I hope to be able to use the FBD model normally on "tree.tre" because it is very common for the root node to have a fossil collection.

**Screenshots**
<img width="707" alt="image" src="https://github.com/revbayes/revbayes/assets/51898298/bf226819-537d-4931-bbf8-272022194a8a">

**Computer info**
I am using a Mac, and the version of RevBayes I am using is development (rapture-2377-ga37213).

**Comment by davidcerny** [comment]
So this is caused by the fact that RevBayes requires the oldest child of the root node to be _strictly younger_ than the start age of the FBD process. The latter is referred to as `process_age` internally, and it can be equal either to the root age _t(r)_, or to some origin age _t(o)_ > _t(r)_. What happens here is that (1) in your tree, one of the children of the root node (t358_1) sits at the end of a zero-length branch, so its age exactly coincides with the age of the root, and (2) you are trying to use the root age as your `process_age`. As a result, the condition is not satisfied.

We could relax that condition a little and only require the oldest child of the root to be _no older_ than `process_age`. But if you try that, it just leads to a different problem, namely the inability to find a viable initial state for the MCMC.

I would suggest that this issue is not really a bug in RevBayes, and should instead be handled by changing your script. Your tree contains a root edge, i.e., it already comes with a _t(o)_ that's distinct from _t(r)_. That makes it natural to set `process_age` equal to the age of origin rather than the root age. We can do so by replacing the `rootAge` argument in the `dnFBDP()` function call by an `originAge` argument. The final question is what we should set it to. You could just manually add the length of your root edge to your origin age (i.e., `originAge = T.rootAge() + 0.1139686245`), or – if that's too inelegant – you can exploit the fact that the root is the last node RevBayes hits when traversing a tree:

```
timetree ~ dnFBDP(originAge           = T.rootAge() + T.branchLength( T.nnodes() ),
                  timeline            = interval_times,
                  lambda              = speciation_rate,
                  mu                  = extinction_rate,
                  psi                 = fossilization_rate,
                  Mu                  = mass_extinction_probabilities,
                  rho                 = sampling_at_present,
                  condition           = "time",
                  taxa                = taxa,
                  initialTree         = T)
```

**Comment by mhDu** [comment]
Dear David,

Thank you so much for your detailed response to my query.

I will follow your advice to modify my script and apologize for initially thinking that the issue I encountered was a bug.

Thank you again for your thoughtful guidance and assistance.

Best,
Minghao
