### ISSUE TITLE
[Feature Request] Implement a `captureOutput` function

### ISSUE THREAD

**Issue by davidcerny** [revbayes/revbayes#523]
**Context:**

I wanted to write an integration test to go with PR #522, but couldn't find a way to print the operator summary to a file. This is because `write()`/`print()` expects a Rev object, and `.operatorSummary()` only returns `NULL`.

Normally, this isn't much of a problem, since we can just redirect stdout to a file:

```
rb_command="source(\"test_MC3/scripts/Test_MC3.Rev\");"
echo $rb_command | ../projects/cmake/build/rb > Test_MC3.txt
```

Job schedulers like Slurm even do this automatically. However, this can't be done from within a Rev script, so it's not an option for validation tests.

**Proposed resolution**

Implement a function similar to R's `capture.output()` that can redirect `std::cout` calls to a stringstream.

**Comment by bredelings** [comment]
I'd prefer to just modify the testing script to capture the standard output.  We would need to chop off the first few lines that display the version number, or perhaps add an option to suppress them.

It also looks like R's `capture.output( )` takes an unevaluated expression as the first argument, and then executes the expression in a modified environment.  I'm not sure we can implement that as a normal RevBayes function -- the revbayes function would just receive the return value of the expression.  In order to modify where the output goes, I think we'd need to modify the interpreter.

**Comment by davidcerny** [comment]
Between #604 and #612, the issue that motivated this feature request has now been solved.
