### ISSUE TITLE
[Help wanted] Partition rate multipliers

### ISSUE THREAD

**Issue by ms609** [revbayes/revbayes#548]
I've been working through the tutorial on [Partitioned data analysis](https://revbayes.github.io/tutorials/partition/) to get my head around how the `branchRates` parameter to `dnPhyloCTMC` works.

The tutorial goes something like:

```rb
# specify a rate multiplier for each partition
part_rate_mult ~ dnDirichlet( rep(10.0, n_data_subsets) )

# Note that here we are dividing two vectors element-wise, i.e., 
# each element of part_rate_mult gets divided by the corresponding
# element of num_sites. Then we multiply the result by sum(num_sites),
# which is just a scalar. This operation ensures that the mean of
# partition-specific branch lengths, weighted by the number of sites
# in each partition, stays equal to the branch lengths we are 
# actually sampling.

part_rate := part_rate_mult / num_sites * sum(num_sites)

# Branch length prior
for (i in 1:num_branches) {
    bl[i] ~ dnExponential(10.0)
    moves.append( mvScale(bl[i]) )
}

TL := sum(bl)
psi := treeAssembly(topology, bl)

for (i in 1:n_data_subsets) {
    seq[i] ~ dnPhyloCTMC(tree=psi, Q=Q[i], branchRates=part_rate[i], type="DNA")
    seq[i].clamp(data[i])
}
```

`part_rate_mult` is a vector of length `n_data_subsets` that sums to 1.

If I had not allowed branch rates to differ between partitions, then each `dnPhyloCTMC` object would exhibit default `branchRates = 1`.  But in the variable branch lengths model, the `branchRates` value for each `dnPhyloCTMC` object has a value smaller than 1.  Dividing the part_rate_mult by the proportion of sites within that partition reduces the absolute value further.

As I understand it, the goal of the `part_rate :=` line is to ensure that the branch lengths in the partitioned model can be interpreted the same way as the branch lengths in a model where branch rates are fixed between partitions.  But I would expect this to be accomplished with `part_rate = n_data_subsets * part_rate_mult`, as this would yield a mean value equal to 1.  If the rate is expressed in units of expected changes per site, I don't understand why we need to multiply it again by the proportion of sites within that partition.

I feel like I'm missing something fundamental about how these calculations work or what they are trying to achieve; if someone could enlighten me I'd be very grateful!

**Comment by davidcerny** [comment]
It was me who wrote this part of the tutorial (or rather, rewrote it from an earlier version that I thought was incorrect) following a Slack discussion with @bredelings – you can probably still find it if you search for the word "multipliers". That said, I can totally see how the explanation might be so condensed that it's not super clear.

> As I understand it, the goal of the `part_rate :=` line is to ensure that the branch lengths in the partitioned model can be interpreted the same way as the branch lengths in a model where branch rates are fixed between partitions. But I would expect this to be accomplished with `part_rate = n_data_subsets * part_rate_mult`, as this would yield a mean value equal to 1.

That was exactly my original instinct as well, but as Ben pointed out, that would only work for equal-sized partitions. Consider a scenario with 300 characters divided into 2 partitions of 100 and 200 characters, respectively. We believe there were 900 total substitutions along the tree, resulting in a prior overall tree length of 900/300 = 3 expected substitutions per character (s/c), but we are uncertain about how these substitutions are distributed across the two partitions. Let's say a particular draw of `part_rate_mult` yields [0.75, 0.25].

Following the calculation from the tutorial, we get `part_rate[1]` = 0.75 / 100 * 300 = 2.25 and `part_rate[2]` = 0.25 / 200 * 300 = 0.375. To get partition-specific expected substitution numbers, we multiply the global tree length expectation (in units of s/c) by the dimensionless partition-specific multiplier, and finally by the number of characters in a given partition. With partition 1 having a multiplier of 2.25 and 100 characters, and partition 2 having a multiplier of 0.375 and 200 characters, we get 3 * 2.25 * 100 + 3 * 0.375 * 200 = 675 + 225 = 900 total expected substitutions, exactly as we initially specified.

If, on the other hand, we did what you propose (and what I originally proposed too!), we'd get `part_rate[1]` = 2 * 0.75 = 1.5 and `part_rate[2]` = 2 * 0.25 = 0.5. This would give us 3 * 1.5 * 100 + 3 * 0.5 * 200 = 450 + 300 = 750 total expected substitutions, and our effective tree length prior would diverge from the intended prior. This simpler calculation would only recover the intended tree length prior if both partitions contained 150 characters each, since 3 * 1.5 * 150 + 3 * 0.5 * 150 = 675 + 225 = 900 total expected substitutions.

**Comment by ms609** [comment]
Thank you – that worked example is very helpful.  Now that I see that the goal is to fix the number of expected changes across the tree, this makes sense. What I'd missed is that the key line is taking a weighted mean (in part because I'd thrown BoDMAS to the wind and placed mental brackets around the multiplication element!)

In fact, I think this was all there in the original explanation in the comment, if I'd perhaps mulled it over more thoroughly.  Would adding brackets and emphasizing the 'weighted mean' aspect be overkill?  I also got diverted by `partition-specific branch lengths`, which led me to think about the lengths of individual branches – perhaps `partition-specific tree length` would have focussed my mind on the partitions' relative contributions to the overall number of changes?  I've proposed this at https://github.com/revbayes/revbayes.github.io/pull/36.

Thanks very much for walking me through this.
