### ISSUE TITLE
Slow convergence with 157-taxon data set

### ISSUE THREAD

**Issue by bredelings** [revbayes/revbayes#58]
While exploring a data set with @jembrown and Ben Toups I found that RevBayes took a long time to converge.  That data set used the Huelsenbeck covarion model, which has 4 mixture components with 8 states each.  In order to simplify matters, I reran the data set using only GTR and no rate variation.

It is quite likely that part of the problem here is that the RevBayes script could be improved a lot.  Maybe a tutorial on speeding up your analyses could address that.

Anyway, for what its worth, I ran the revbayes script for about 25 minutes, and also ran bali-phy at the same time for the same length of time, on the same machine (with a fixed alignment).  BAli-Phy does not have SSE-optimized routines for computing the likelihood or anything of that sort, and yet mixes substantially better.  A comparison with phylobayes would also be a good idea, but I haven't done that.

This seems to me to indicate that it would be possible to speed up RevBayes analyses quite substantially by (i) using an improved peeling algorithm with a virtual root (ii) doing a so-called "lazy SPR", where you consider attaching a number of adjacent branches (perhaps all branches) instead of just one branch.

**Comment by bredelings** [comment]
Here's the GTR model script and data.
[Amphibians_ATP6.nex.txt](https://github.com/revbayes/revbayes/files/4446062/Amphibians_ATP6.nex.txt)

[gtr3.Rev.txt](https://github.com/revbayes/revbayes/files/4446059/gtr3.Rev.txt)

**Comment by bredelings** [comment]
![tree1](https://user-images.githubusercontent.com/140268/78699248-71fdde80-78b8-11ea-994d-a985b0cc967a.png)
Here's the tree mixing MDS/PCA plot for revbayes.

**Comment by bredelings** [comment]
![tree1](https://user-images.githubusercontent.com/140268/78699362-9f4a8c80-78b8-11ea-9733-45d22e62e106.png)

Here's the tree mixing MDS/PCA plot for bali-phy

**Comment by bredelings** [comment]
![tree1](https://user-images.githubusercontent.com/140268/78702131-f81c2400-78bc-11ea-9fa2-7a712da0f53b.png)

Here's the tree mixing MDS/PCA plot for bali-phy.

BAli-Phy didn't converge in 25 minutes either, the comparison might be clearer for a longer run, like 2 hours.

**Comment by bredelings** [comment]
![tree1](https://user-images.githubusercontent.com/140268/78703718-8c878600-78bf-11ea-967e-0875b5770a11.png)

Here's the tree mixing for bali-phy with 10% burnin removed.

**Comment by bredelings** [comment]
![tree-1-2](https://user-images.githubusercontent.com/140268/78704419-ac6b7980-78c0-11ea-9673-fb7ce89e3f58.png)

Here is a combined MDS plot.  The Blue is revbayes, which has not reached the equilibrium yet, and the red is bali-phy, which seems closer to the equilibrium.  To be clearer I should probably do two revbayes chains, and two bali-phy chains for a longer period.

**Comment by afmagee** [comment]
This doesn't solve the underlying convergence issues, but here's a script that runs about 3x faster by changing the setup of the tree. 

Instead of using `dnUniformTopology` with `treeAssembly`, it uses `dnUniformTopologyBranchLength`. This requires a change of branch length moves to `mvBranchLengthScale`, and for now I have kept the weight on branch length moves the same.

Further optimizations on speed may be possible by reducing the number of branch length moves further. But this would be a minor improvement at best, as cutting the number in half produced only a roughly 10% increase in iterations per unit time.

I ran the new script for 1000 burnin iterations and then 3000 iterations sampling every 10. That produced the attached convergence plot, where I think things are stable after about the 100th sample, or 1000th post-burnin iteration. The plot is of the RF distance between tree[i] and tree[1], which is basically how [Lanfear _et al._ (2015)](https://academic.oup.com/gbe/article/8/8/2319/2198217) get at convergence. If I calculate the ESS of this quantity, it's 5 over all 300 samples and 26 after 100, which backs up the eyeball test that things are stable.

![Screenshot from 2020-04-07 12-32-38](https://user-images.githubusercontent.com/20982731/78711484-e5f5b200-78cb-11ea-9c53-f371150cf6fb.png)


[gtr3_revised.Rev.txt](https://github.com/revbayes/revbayes/files/4446588/gtr3_revised.Rev.txt)

**Comment by bredelings** [comment]
@afmagee Another approach is just to run two chains for an hour and compute ASDSF.  I'm trying your script now.

**Comment by bredelings** [comment]
![tree-1-2](https://user-images.githubusercontent.com/140268/78717227-29085300-78d5-11ea-9ea9-821a05a81d11.png)

2 RevBayes runs for 35 minutes using dnUniformTopologyBranchLength and mvBranchLengthScale

**Comment by bredelings** [comment]
![tree-1-2](https://user-images.githubusercontent.com/140268/78717362-5523d400-78d5-11ea-8c5a-4f4f397d031b.png)

2 bali-phy runs.
ASDSF = 0.02

**Comment by bredelings** [comment]
I wonder if the treeAssembly function copies the tree data structure whenever any branch length changes.  That would easily cause O(B^2) behavior for B branches.

**Comment by bredelings** [comment]
I also note that using `dnUniformTopologyBranchLength` doesn't allow constructing branch lengths as a deterministic node.  For example,
```
for (i in 1:n_branches) {
  temp ~ dnGamma(0.5,0.5*n_branches)
  branch_length[i] = tree_length * temp
}
```

**Comment by afmagee** [comment]
You can achieve the same effect of compound branch-length models in a roundabout way.

```
psi ~ dnUniformTopologyBranchLength(taxa,branchLengthDistribution=dnGamma(0.5,0.5*n_branches))
raw_tree_length := psi.treeLength()
tree_length ~ dnLognormal(log(1),1.17481)
tree_length_adjustor := tree_length/raw_tree_length
.
.
.
seq ~ dnPhyloCTMC(tree=psi,branchRates=tree_length_adjustor)
```


I'm not seeing any obvious issues of extra tree copying that would cause the speed issue at a quick glance.

**Comment by btoup15** [comment]
When trying to implement the most recent suggestion, I ran into a problem. When defining tree_length and calling the log() function, RevBayes expects a RealPos value. As it's currently written, 1 is treated as a constant, so you would need to do 1+0.0 in order to convert 1 to a RealPos on the fly. In addition, the log function requires you specify the base as well or else it throws an error, did you have base e (natural log) in mind when you were writing this? Also if anyone has a more elegant solution to what I just described let me know.

**Comment by afmagee** [comment]
Yes, you're correct that this code doesn't work as written. I switch between R and Rev too much, I do this to myself all the time and have had to debug too many log() errors where I should have used ln().

Just replace `tree_length ~ dnLognormal(log(1),1.17481)` with `tree_length ~ dnLognormal(ln(1.0),1.17481)` and you're in business, or even just replace `ln(1.0)` with `0.0` directly.

I also don't know that I recommend ln(1.0) as an all-purpose log-mean. This produces a tree length prior with a 95% CI of [0.1,10] and a median of 1, which is generally reasonable but perhaps not the best prior for all cases. If you know your tree is likely longer or shorter, replace 1.0 with a variable theta. Controlling the CI is easy too, using H=0.587405. The prior median will be theta, and the prior CI will span H orders of magnitude around the median. So if you're more confident in your prior median being reasonable, you can just use H as the Lognormal sigma parameter instead of 2H.

**Comment by btoup15** [comment]
That works! The script now runs okay, but looking at my output files it seems like the toplogy is no longer changing (each output tree has the same topology). I'll attach the script I'm using here, do you see anything wrong with this that may cause that?
[covarion_COX1_test.txt](https://github.com/revbayes/revbayes/files/4518185/covarion_COX1_test.txt)

**Comment by afmagee** [comment]
Try it now.

[covarion_COX1_test.txt](https://github.com/revbayes/revbayes/files/4518200/covarion_COX1_test.txt)

**Comment by btoup15** [comment]
So it looks like you re-added the branch length and topology moves which makes sense, but currently the topology variable isn't referenced in the model anywhere so you get a missing variable error when running the script. Previously, topology was referenced in the psi variable when calling the treeassembly function, but the new dnUniformTopologyBranchLength way of defining psi doesn't take topology as an argument.
Was there a miscommunication and should topology be defined by the dnUniformTopologyBranchLength function, and then psi still be defined by treeassembly?
I'm a little confused by the current setup as it doesn't seem to take toology into account anywhere

**Comment by afmagee** [comment]
Whoops, topology == psi in the new moves added.

The bottom line is that you need to put moves on the tree. The tree is `psi` here, not `topology` (which no longer exists). If there's no move on the tree, MCMC will never perturb it. Same for the branch lengths.

The unrooted tree moves will take a pure-topology object or a topology+branch lengths object as their DAG node to perturb, so other than making sure you give it an object that actually exists (whoops), the moves on the tree are unchanted.

The main difference between using `dnUniformTopologyBranchLength` object and `dnUniformTopology` is how you interact with the branch lengths. You need `mvBranchLengthScale` when using `dnUniformTopologyBranchLength` to move branch lengths. And this move you simply point at the tree and it handles the rest, just note that it only perturbs a single branch per move, so the weight should be proportional to the number of branches in the tree, not a constant.

[covarion_COX1_test.txt](https://github.com/revbayes/revbayes/files/4518494/covarion_COX1_test.txt)

**Comment by btoup15** [comment]
Thanks for your help on this! That looks like it's working now, but it's slowed my runtime down a bunch for some reason (went from 10 generations taking about 30 seconds to now 1 generation taking over a minute). Maybe it's because this script is running a covarion model rather than the plain GTR that you were testing with?

**Comment by afmagee** [comment]
Presumably. Covarion rate matrices are bigger than standard GTRs and you've got mixtures of site matrices. Computing the likelihood of a site under an 8x8 matrix 16 times (4 matrices and discrete gamma) is a lot slower than computing it under a 4x4 matrix 4 times.

**Comment by btoup15** [comment]
That makes sense! Well it looks like this new method of tree construction takes quite a bit longer than the original method when using the covarion, so I might be forced to stick with the old method for now.
