### ISSUE TITLE
How to set up and use rb-mpi?

### ISSUE THREAD

**Issue by chlangley** [revbayes/revbayes#621]
I would like to use mpi, particularly to routinely run replicates (as I have seen alluded to in various revbayes discussions).

I downloaded, compiled and installed 1.2.4 (both rb and rb-mpi) on my mac M1.  rb works as expected.  

While mpi seems to test fine on the open-mph.org test examples, I realize I don't have code (scripts) and data examples and expected output for rb-mpi.  I have searched.

It is not clear to me how much mpi messaging is build into revbayes.  

Can someone direct me to a tutorial or full documentation or a working example, please?

**Comment by davidcerny** [comment]
It's not entirely clear to me what's being asked here, but here is my best attempt to answer:

(1) There is no special set up for the MPI version beyond compiling it, which you've already done. Your Rev scripts will look identical regardless of whether you execute them using the single-core version or the MPI version.

(2) We do have two tests with MPI-specific expected output, although our [test runner](https://github.com/revbayes/revbayes/blob/development/tests/run_integration_tests.sh) currently doesn't check for it, so I can't vouch for it being up-to-date. Here they are:

- [`test_multiple_mcmc/output_expected_mpi`](https://github.com/revbayes/revbayes/tree/development/tests/test_multiple_mcmc/output_expected_mpi)
- [`test_steppingstone/output_expected_mpi`](https://github.com/revbayes/revbayes/tree/development/tests/test_steppingstone/output_expected_mpi)

(3) As far as I'm aware, there are three common use cases for the MPI version:

- Parallelizing a regular MCMC analysis with multiple runs: `mcmc(..., nruns = 4)`
- Parallelizing a MC^3 analysis with multiple heated chains per run: `mcmcmc(..., nchains=4)`
- Parallelizing a marginal likelihood analysis with multiple power posteriors: `powerPosterior(..., cats=63)`

**Comment by wrightaprilm** [comment]
In addition to David's excellent answer, I start mpi RevBayes from the command line like so:

`mpirun -np 4 rb-mpi myScript.Rev`

The above would be for 4 cores.

**Comment by chlangley** [comment]
Great.  Thanks.  Perhaps I have an mpi set up issue involving access to tmpdir (TMPDIR)?

```
tests > mpirun -np 4 rb-mpi test_basics/scripts/basics.Rev
[camus.ucdavis.edu:74298] shmem: mmap: an error occurred while determining whether or not /var/folders/xn/pc3b349x2_lftfkyd5rjn6n80000gs/T//ompi.camus.505/jf.0/3274964993/sm_segment.camus.505.c3340001.0 could be created.
...

```

**Comment by wrightaprilm** [comment]
Is this an HPC unit? You might double check if mpi is enabled and if a module needs to be loaded before running it.

**Comment by davidcerny** [comment]
@chlangley It might not have to do with access per se but with path length:

https://github.com/open-mpi/ompi/issues/7393#issuecomment-956438971
https://github.com/open-mpi/ompi/issues/12784#issuecomment-2321021616

**Comment by ms609** [comment]
I think I recall a similar TMPDIR issue when running using singularity – not sure this is the issue here, but for me the solution was to link the TMPDIR using

`mpirun singularity run -B $TMPDIR:$TMPDIR --app rbmpi ../../../revbayes-v1.2.4-linux64-singularity.simg myscript.Rev`


I'm running tasks using slurm.  My HPC slurm template suggested requesting multiple cores with
```          
#SBATCH -c 16
``` 
but RevBayes only uses one core on this configuration.  I had to request nodes, rather than cores, by replacing this with
```
#SBATCH -n 16
```

then RevBayes runs in MPI mode when executed with 
```
mpirun ../revbayes/projects/cmake/build-mpi/rb-mpi myscript.Rev
```

As I say, not sure how much of this will apply to your situation, but hopefully something comes in useful!

**Comment by davidcerny** [comment]
Have you managed to resolve this problem @chlangley?

**Comment by davidcerny** [comment]
Hmm... since I have no issues running the MPI version on my own macOS/ARM64 machine (M3 Max, Sequoia 15.1.1), this indeed seems like an MPI configuration problem rather than a bug inherent to RevBayes. I'm glad you were able to at least circumvent it if not resolve it, so I'm closing this as you suggest.

Issue #428 remains open, and does indeed currently make it a pain to use the MPI version for multiple MCMC runs. It is on our radar.
