### ISSUE TITLE
Consensus tree crash

### ISSUE THREAD

**Issue by JMoysiuk** [revbayes/revbayes#68]
The consensus tree function crashes the program without an error message.
```
treetrace = readTreeTrace("mk.trees", treetype="non-clock", burnin=0.25, nruns=2) #this line works fine
mrc_tree = consensusTree(trace=treetrace, cutoff=0.5, file="MRcon.tree") #this line causes the program to crash and close, seemingly in the annotation phase
```
I attach the files I am using (extensions changed to txt so I could upload).
I am running version 1.0.12 on Windows 8. 
Thanks for any help you can provide. 
[mk.trees.txt](https://github.com/revbayes/revbayes/files/4587489/mk.trees.txt)
[mk_run_1.trees.txt](https://github.com/revbayes/revbayes/files/4587490/mk_run_1.trees.txt)
[mk_run_2.trees.txt](https://github.com/revbayes/revbayes/files/4587491/mk_run_2.trees.txt)
[mrc_problem.rev.txt](https://github.com/revbayes/revbayes/files/4587492/mrc_problem.rev.txt)

**Comment by bredelings** [comment]
There appears to be a segfault in `TreeSummary::annotateTree` at line 800: https://github.com/revbayes/revbayes/blob/development/src/core/analysis/mcmc/output/TreeSummary.cpp#L800

This is because the `node_ages` array is empty.  It looks like this array holds branch lengths for unrooted trees (as in this case) by node ages for rooted trees.  The fact that this array is empty seems to indicate that the split for this branch has not been seen in any of the sampled trees.  That should be impossible, since the split should be in more than half of the input trees in order to be in the consensus tree.

**Comment by JMoysiuk** [comment]
Thanks for checking into this so quickly. To clarify, do you think there's something I can do to get around this bug or is this something that will have to be fixed in a software update?

**Comment by bjoelle** [comment]
@JMoysiuk this issue should now be resolved in the `development` branch - please reopen this issue if you still have problems
