### ISSUE TITLE
Conversion between Integer and NaturalNumber to RealPos

### ISSUE THREAD

**Issue by hoehna** [revbayes/revbayes#99]
RealPos is defined in some parts of the code as > 0.0 and sometimes as >= 0.0. We need some consistent definitions if Natural and RealPos are >0 or >=0! 

See the example code:
a = 1 - 1 # making sure a is an integer
type(a)
a   # the value is indeed 0
sqrt(a)    # throws an error

b = 0
type(b)
b   # the value is indeed b
sqrt(b)    # works

**Comment by willpett** [comment]
It seems clear that the definition of `RealPos` should be >0.
For `Natural` I think we currently use primarily >=0, which is the ISO definition.

Shall we agree on those?

**Comment by bredelings** [comment]
Could you have 2 types: RealPos (x > 0) and RealNonNeg (x >= 0)?  It seems like sqrt(x) wants x>=0, but log(x) probably wants x > 0.

It seems like there are eventually going to be some functions that have a range like (1,\infty], and it seems difficult to make a type for every domain.  It looks like Mathematica has names for the following domains: Reals, NegativeReals, NonNegativeReals, NonPositiveReals.

What are the downsides of eliminating RealPos, and doing this kind of domain checking inside the functions?

**Comment by willpett** [comment]
Oh, I guess I like the idea of `RealNonNeg`. Didn't think about how some functions are defined for reals >=0.

**Comment by bredelings** [comment]
Hmmm.... so practically, you could make a function like `domain_check(x, range)` to warn or throw a domain error in a uniform fashion.  You could create functions like NegativeReals() to construct a range object in a way that makes for readable code.

The current practice of having functions alter the type of the arguments they are called with (I think) is weird and has created problems in the past.  This seems to result from the fact that some types are logically nested (i.e. RealPos is a subset of Real) but mutually exclusive in the implementation -- i.e. a variable can't be both Real and RealPos at the same time.  Also, if you had a random variable that was Real, should it temporarily also be RealPos during the time it is negative?

**Comment by willpett** [comment]
That is a fair point. A function may be defined only for `RealPos` for example, but may accept a `Real` because it happens to have a positive value and is therefore convertible to `RealPos`. In the event that the MCMC samples a non-positive value for that variable, the return value of the function is no longer defined, and I am not sure what happens in this case actually. It probably depends on the function, so you are back to function-specific implementation issues anyway.

**Comment by willpett** [comment]
A `Real` should not also be a `RealPos` during the time it is positive, because that would mean it can be accepted by functions that are only defined for `RealPos`, whereas non-positive values of the variable can be sampled during MCMC. (I deleted my previous comment... After testing some things, I see that I was wrong.)

What is an example of a problem this has caused in the past?

**Comment by bredelings** [comment]
So, `Real` versus `RealPos` does not describe the _current_ value of a variable, but the range of _possible_ values for a variable.  Is this principle consistently and coherently followed?

If I remember correctly (which I might not), https://github.com/revbayes/revbayes/issues/14 was a result of the mean( ) and sum( ) functions altering the type of their argument.

**Comment by bredelings** [comment]
Another idea would be, instead of modifying the argument's type, to add a type-conversion node.  For example, you could create an IntegerToReal function when passing a variable of type Integer to a function that wants a Real.  You could also implement a SimplexToRbVector conversion function.
